defmodule Exscrabble do
  @moduledoc """
  Documentation for `Exscrabble`.
  """

  @doc """
  Hello world.

  ## Examples

      iex> Exscrabble.hello()
      :world

  """
  def find_next_optimum_move() do
  end

  def read_input() do
    hand = "BD"

    board_string = """
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    ...............
    ....AN.YU......
    """

    Board.new(board_string, hand)
    |> Board.find_possible_words(DictionaryWord.read_from_file)
  end
end